### ISSUE TITLE
Have some trouble with 03-emotion-analysis.ipynb

### ISSUE THREAD

**Issue by SpikeWong** [georgia-tech-db/eva#788]
### Search before asking

- [X] I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar questions.

### Question

When I was following instruments of the tourial 03-emotion-analysis.ipynb, I had some troubles.
```
response = cursor.execute('DROP TABLE IF EXISTS HAPPY').fetch_all().as_df()
print(response)
cursor.execute('LOAD VIDEO "defhappy.mp4" INTO HAPPY').fetch_all().as_df()
```
It reported 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 response = cursor.execute('DROP TABLE IF EXISTS HAPPY').fetch_all().as_df()

AttributeError: 'NoneType' object has no attribute 'fetch_all'
```
And I found some error logs from eva.log
```
Traceback (most recent call last):
  File "/Users/apple1/.pyenv/versions/3.8.15/bin/eva_server", l05-28-2023 17:00:59 WARNING[drop_executor:drop_executor.py:exec:0046] Table: HAPPY does not exist
/site-packages/eva/eva_server.py", line 100, in main
    asyncio.run(start_eva_server(host=host, port=int(port)))
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/site-packages/eva/eva_server.py", line 39, in start_eva_server
    await eva_server.start_eva_server(host, port)
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/site-packages/eva/server/server.py", line 43, in start_eva_server
    self._server = await asyncio.start_server(self.accept_client, host, port)
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/asyncio/streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/Users/apple1/.pyenv/versions/3.8.15/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 8803): address already in use
```
I am not sure if there are some steps missed in the tourial(eg. create the happy table) or my incorrect configuration.

**Comment by gaurav274** [comment]
Hello, @SpikeWong! I appreciate your interest in `evadb`. According to the error logs, it appears that the server is currently active and attempting to initiate another instance. This shouldn't pose a problem as long as the server remains operational.

Regarding the error itself, my suspicion is that it can be due to an outdated version of `evadb`. Would you mind providing information about the specific version of `evadb` you are currently using?

**Comment by jarulraj** [comment]
Closing this due to lack of response. Please reopen if needed.
